-- (c) Manuel Alejandro Gómez Nicasio <az-dev@outlook.com>
--
-- For the full copyright and license information, please view the LICENSE
-- file that was distributed with this source code.

--
-- ARRAY_LENGTH
--      https://www.postgresql.org/docs/17/functions-array.html#ARRAY-FUNCTIONS-TABLE
-- ARRAY_REMOVE
--      https://www.postgresql.org/docs/current/functions-array.html#ARRAY-FUNCTIONS-TABLE
--

WITH TOYS AS (
    SELECT TOY_ID, TOY_NAME, PREVIOUS_TAGS, UNNEST(PREVIOUS_TAGS) AS PREVIOUS_TAG_ITEM, NEW_TAGS, UNNEST(NEW_TAGS) AS NEW_TAG_ITEM
    FROM TOY_PRODUCTION
),
TAG_DIFFS AS (
    SELECT
        TOY_ID
        , TOY_NAME
        , ARRAY_REMOVE(ARRAY_AGG(DISTINCT CASE WHEN NOT (NEW_TAG_ITEM = ANY (PREVIOUS_TAGS)) THEN NEW_TAG_ITEM END), NULL) AS ADDED_TAGS
        , ARRAY_REMOVE(ARRAY_AGG(DISTINCT CASE WHEN NEW_TAG_ITEM = ANY (PREVIOUS_TAGS) AND NEW_TAG_ITEM = ANY (NEW_TAGS) THEN NEW_TAG_ITEM END), NULL) AS UNCHANGED_TAGS
        , ARRAY_REMOVE(ARRAY_AGG(DISTINCT CASE WHEN NOT (PREVIOUS_TAG_ITEM = ANY (NEW_TAGS)) THEN PREVIOUS_TAG_ITEM END), NULL) AS REMOVED_TAGS
    FROM TOYS
    GROUP BY TOY_ID, TOY_NAME
)
SELECT 
    TOY_ID
    , TOY_NAME
    , ADDED_TAGS
    , UNCHANGED_TAGS
    , REMOVED_TAGS
    , COALESCE(ARRAY_LENGTH(ADDED_TAGS, 1), 0) AS TOTAL_ADDED_TAGS
    , COALESCE(ARRAY_LENGTH(UNCHANGED_TAGS, 1), 0) AS TOTAL_UNCHANGED_TAGS
    , COALESCE(ARRAY_LENGTH(REMOVED_TAGS, 1), 0) AS TOTAL_REMOVED_TAGS
FROM TAG_DIFFS
ORDER BY TOTAL_ADDED_TAGS DESC




--
-- ARRAY_LENGTH
--      https://www.postgresql.org/docs/17/functions-array.html#ARRAY-FUNCTIONS-TABLE
-- ARRAY_AGG ... FILTER ...
--      https://www.postgresql.org/docs/17/functions-aggregate.html#FUNCTIONS-AGGREGATE-TABLE
--      https://www.postgresql.org/docs/17/sql-expressions.html#SYNTAX-AGGREGATES
--

WITH TOYS AS (
    SELECT TOY_ID, TOY_NAME, UNNEST(PREVIOUS_TAGS) AS PREVIOUS_TAGS, UNNEST(NEW_TAGS) AS NEW_TAGS
    FROM TOY_PRODUCTION TP
)
SELECT *
    , COALESCE((ARRAY_LENGTH(ADDED_TAGS, 1)), 0) AS TOTAL_ADDED_TAGS
    , COALESCE((ARRAY_LENGTH(UNCHANGED_TAGS, 1)), 0) AS TOTAL_UNCHANGED_TAGS
    , COALESCE((ARRAY_LENGTH(REMOVED_TAGS, 1)), 0) AS TOTAL_REMOVED_TAGS
FROM (
    SELECT DISTINCT
        TOY_ID
        , TOY_NAME
        , (
            SELECT ARRAY_AGG(T) FILTER (WHERE T IS NOT NULL)
            FROM (
                SELECT NEW_TAGS AS T FROM TOYS WHERE TOYS.TOY_ID = T.TOY_ID
                EXCEPT
                SELECT PREVIOUS_TAGS AS T FROM TOYS WHERE TOYS.TOY_ID = T.TOY_ID
            ) T
        ) AS ADDED_TAGS
        , (
            SELECT ARRAY_AGG(T) FILTER (WHERE T IS NOT NULL)
            FROM (
                SELECT NEW_TAGS AS T FROM TOYS WHERE TOYS.TOY_ID = T.TOY_ID
                INTERSECT
                SELECT PREVIOUS_TAGS AS T FROM TOYS WHERE TOYS.TOY_ID = T.TOY_ID
            ) T
        ) AS UNCHANGED_TAGS
        , (
            SELECT ARRAY_AGG(T) FILTER (WHERE T IS NOT NULL)
            FROM (
                SELECT PREVIOUS_TAGS AS T FROM TOYS WHERE TOYS.TOY_ID = T.TOY_ID
                EXCEPT
                SELECT NEW_TAGS AS T FROM TOYS WHERE TOYS.TOY_ID = T.TOY_ID
            ) T
        ) AS REMOVED_TAGS
    FROM (
        SELECT * FROM TOYS
    ) T
) T
ORDER BY ARRAY_LENGTH(ADDED_TAGS, 1) DESC
