-- (c) Manuel Alejandro Gómez Nicasio <az-dev@outlook.com>
--
-- For the full copyright and license information, please view the LICENSE
-- file that was distributed with this source code.

--
-- old fashioned self-join
--

SELECT
    TP1.PRODUCTION_DATE
    , TP1.TOYS_PRODUCED
    --, TP2.PRODUCTION_DATE AS PREVIOUS_DATE
    , TP2.TOYS_PRODUCED AS PREVIOUS_DATE_PRODUCTION
    , TP1.TOYS_PRODUCED - TP2.TOYS_PRODUCED AS PRODUCTION_CHANGE
    , ROUND((100.00 * (TP1.TOYS_PRODUCED - TP2.TOYS_PRODUCED)) / TP2.TOYS_PRODUCED, 2) AS PRODUCTION_CHANGE_PERCENTAGE
FROM
    TOY_PRODUCTION TP1
    JOIN TOY_PRODUCTION TP2 ON TP1.PRODUCTION_DATE - 1 = TP2.PRODUCTION_DATE
ORDER BY PRODUCTION_CHANGE_PERCENTAGE DESC

